### ISSUE TITLE
Add: Use same variable value multiple times on one page

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-ALAutomatedTestingTests#99]
Note for framework: there should be no error, just a message and a few lines in the report to warn developers.

eg:
``` yml
fields:
  - no label: repeate_var_val
    datatype: checkbox
    choices:
    - First appearance: repeated_val
    - Second appearance: repeated_val
```
